version: "3.9"
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - bot-db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  bot-db-data:  # /var/lib/docker/volumes/bot-db-data