from aiogram.fsm.state import StatesGroup, State


class States(StatesGroup):
    waiting_for_add_comment = State()
    waiting_for_save_pattern_name = State()
    waiting_for_search_after_confirm = State()
    waiting_for_search_before_confirm = State()
    waiting_for_search = State()
    waiting_for_edit_list_order = State()
    # ================================================
    waiting_for_general_clinic = State()
    waiting_for_add_birth_date_people_one = State()
    waiting_for_add_phone_people_one = State()
    waiting_for_add_email_people_one = State()
    waiting_for_add_address_people_one = State()
    waiting_for_add_fio_people_one = State()
    waiting_for_edit_fio_people_one = State()
    waiting_for_edit_birth_date_people_one = State()
    waiting_for_edit_phone_date_people_one = State()
    waiting_for_edit_email_date_people_one = State()
    waiting_for_edit_address_date_people_one = State()
    # =================================================
    waiting_for_others_one = State()
    waiting_for_others_two = State()
    waiting_for_others_three = State()
    # =================================================
    waiting_for_edit_address_user = State()
    waiting_for_edit_email_user = State()
    waiting_for_edit_phone_user = State()
    waiting_for_edit_birth_date_user = State()
    waiting_for_edit_patronymic_user = State()
    waiting_for_edit_female_user = State()
    waiting_for_edit_fio_user = State()
    waiting_for_fio = State()
    waiting_for_female = State()
    waiting_for_patronymic = State()
    waiting_for_birth_day = State()
    waiting_for_phone = State()
    waiting_for_email = State()
    waiting_for_address = State()
    waiting_for_reply_menu = State()
    # ====================================================
    CHOOSING_SPEC = State()
    CHOOSING_COURSE = State()
    CHOOSING_TYPE = State()
    TYPING = State()
